config/routes.rb
Travel::Application.routes.draw do
  devise_for :users

  namespace :admin do
    root :to => "articles#index"

    get 'category', :controller => 'articles', :action => 'category'
    get 'scenic_spots', :controller => 'articles', :action => 'scenic_spots'
    get 'tourist_route', :controller => 'articles', :action => 'tourist_route'

    get 'articles/category', :controller => 'articles', :action => 'category'
    match 'articles/update_category', :controller => 'articles', :action => 'update_category'
    match 'articles/:id/delete_image/:image_id', :controller => 'articles', :action => 'delete_image', :as => "delete_image"
    match 'categories/destroy/:id',  to: 'categories#destroy', as: :destroy

    resources :categories, except: :destroy
    resources :articles
  end

  root :to => 'index#index'

  match ':controller(/:action(/:id))(.:format)'
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/admin/article.rb
class Admin::Article < ActiveRecord::Base
  self.table_name = "articles"
  attr_accessible :content, :created_at, :like, :title, :updated_at, :views, :tour_pictures, :tour_pictures_attributes, :tour_code, :quotation

  has_many :article_category
  has_many :categories , :through => :article_category
  has_many :tour_pictures, :dependent => :destroy
  accepts_nested_attributes_for :tour_pictures, :allow_destroy => true

  def html_content
    self.content.html_safe
  end

  def none_html_content
    self.content.html_safe.gsub(/<.*?>/, "")[0..200]+"..."
  end

  def is_tourist_route?
    self.is_tourist_route
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!

  Category.all.map(&:name).each do |category|
    define_method(category.gsub(/ /, "_").downcase) do
      @category = Category.find_by_name(category)
      render :template => "admin/articles/category", :locals => {:articles => Admin::Article.all }
    end
  end
  
  def tourist_route
    articles = Admin::Article.all.select{|x|x.is_tourist_route==true}
    render :template => "admin/articles/index", :locals => {:articles => articles}
  end

  def scenic_spots
    @categories = Category.all.select{|x|x.scenic_spots==true}    #scenic_spots
    @articles = Admin::Article.all.select{|x|x.is_tourist_route==true}   #tourist_route
    @require_str = ""
    @categories.each do |category|
      if category.id == @categories.first.id
        @require_str += "\'#{category.format_name}=\'+$(\'##{category.format_name}\').val()"
      else
        @require_str += "+\'&#{category.format_name}=\'+$(\'##{category.format_name}\').val()"
      end
    end
    @require_str += "+\"&from=scenic_spots\""
    @require_str = @require_str.html_safe
    render :template => "admin/articles/category"
  end

  # Column Menu
  def category
    @categories = Category.all.select{|x|x.scenic_spots==false}
    @articles = Admin::Article.all.select{|x|x.is_tourist_route==true}

    @require_str = ""
    @categories.each do |category|
      if category.id == @categories.first.id
        @require_str += "\'#{category.format_name}=\'+$(\'##{category.format_name}\').val()"
      else
        @require_str += "+\'&#{category.format_name}=\'+$(\'##{category.format_name}\').val()"
      end
    end
    @require_str += "+\"&from=category\""
    @require_str = @require_str.html_safe
  end

  # GET /admin/articles
  # GET /admin/articles.json  
  def index
    @admin_articles = Admin::Article.all.select{|x|x.is_tourist_route==false}
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_articles }
    end
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
    @admin_article = Admin::Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_article }
    end
  end

  # GET /admin/articles/new
  # GET /admin/articles/new.json
  def new
    @admin_article = Admin::Article.new
    5.times { @admin_article.tour_pictures.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_article }
    end
  end

  # GET /admin/articles/1/edit
  def edit
    @admin_article = Admin::Article.find(params[:id])
    5.times { @admin_article.tour_pictures.build }
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(params[:admin_article])

    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to @admin_article, notice: 'Article was successfully created.' }
        format.json { render json: @admin_article, status: :created, location: @admin_article }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/articles/1
  # PUT /admin/articles/1.json
  def update
    @admin_article = Admin::Article.find(params[:id])
    @admin_article.format_title = @admin_article.title.gsub(/ /,"_").downcase

    respond_to do |format|
      if @admin_article.update_attributes(params[:admin_article])
        format.html { redirect_to @admin_article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article = Admin::Article.find(params[:id])
    @admin_article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.json { head :no_content }
    end
  end

  def update_category
    Category.all.each do |category|
      next if params[category.format_name].nil?
      ids = params[category.format_name].split(",")
      if params[:from]=="category"
        category.super_category = params[category.format_name]
        category.save
      else
        Category.find_by_format_name(category.format_name).article_ids = ids 
      end
    end
    render :json => {
      :connect_success => true
    }
  end

  def delete_image
    @tour_picture = TourPicture.find(params[:image_id])
    @tour_picture.image.destroy
    @tour_picture.image.clear
    @tour_picture.delete
    respond_to do |format|
      format.html { redirect_to edit_admin_article_path(params[:id]) }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= javascript_include_tag "ckeditor/ckeditor.js" %>  
<%= form_for(@admin_article) do |f| %>
  <% if @admin_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_article.errors.count, "error") %> prohibited this admin_article from being saved:</h2>

      <ul>
      <% @admin_article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <label class="control-label" for="events"><%= f.label :title %></label>
    <div class="controls">
      <%= f.text_field :title %>  
    </div>
  </div>
  <% if f.object.is_tourist_route? %>
  <div class="control-group">
    <label class="control-label" for="events"><%= f.label :tour_code %></label>
    <div class="controls">
      <%= f.text_field :tour_code %>  
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="events"><%= f.label :quotation %></label>
    <div class="controls">
      <%= f.text_field :quotation %>  
    </div>
  </div>
  <% end %>
  <div class="control-group">
    <label class="control-label" for="events"><%= f.label :content %></label>
    <div class="controls">
      <%= f.cktext_area :content, :rows=>8, :style => "width: 500px;" %>
    </div>
  </div>
  <br />
  <% @admin_article.tour_pictures.each do |x|%>
    <%= image_tag x.image(:normal) if !x.id.nil?%>
    <%#= link_to( "x", {:controller => "articles", :action => "delete_image"}) %>
    <% if !x.id.nil? %>
    <%= link_to 'X', admin_delete_image_path(@admin_article.id, x) %>
    <% end %>
  <% end %>

  <div class="newPaperclipFiles">
    <%= f.fields_for :tour_pictures do |asset| %>
      <% if asset.object.new_record? %>
        <%= asset.file_field :image %>
      <% end %>
    <% end %>
  </div>

  <div class="existingPaperclipFiles">
    <% f.fields_for :tour_pictures do |asset| %>
      <% unless asset.object.new_record? %>
        <div class="thumbnail">
          <%= link_to( image_tag(asset.object.image.url(:thumb)), asset.object.image.url(:original) ) %>
          <%#= asset.check_box :_delete %>
        </div>
      <% end %>        
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/articles/category.html.erb
  <SCRIPT src="http://code.jquery.com/jquery-migrate-1.1.1.js"></SCRIPT>
  <%= stylesheet_link_tag "admin/chosen" %>
<% if params[:action]=="scenic_spots" %>
  <h1>Select Tourist Route for Scenic Spots</h1>
  <%= link_to 'New Scenic Spots', new_admin_category_path, {:class=>"pull-right"} %>
<% else %>
  <h1>Select Articles for Category</h1>
<% end %>
<br />

<% @categories.each do |category| %>
  <div class="control-group display-flex">
    <label class="control-label" for="events">
      <%= category.name.titleize %>
      <% if params[:action]=="scenic_spots" %>
        (<%= link_to 'Eidt',edit_admin_category_path(category)%>&nbsp;|&nbsp;<%= link_to 'Delete',admin_destroy_path(category) , method: :delete, data: { confirm: 'Are you sure?' }%>)
      <% end %>
      <span class="category-label">(Please select <%= category.row_num %> articles for this category.)</span>
    </label>
    <div class="controls">
      <% if params[:action]=="scenic_spots" %>
        <%= select_tag category.name.gsub(/ /, "_").downcase, options_for_select(@articles.collect{|u|[u.title,u.id]}, :selected => category.articles.map(&:id)), class: 'chzn-select', style:"width:500px", multiple: true%>
      <% else %>
        <%= select_tag category.name.gsub(/ /, "_").downcase, options_for_select(Category.find_all_by_scenic_spots(1).collect{|u|[u.name,u.id]}, :selected => (category.super_category.split(",").present? ? category.super_category.split(",") : nil)), class: 'chzn-select', style:"width:500px", multiple: true%>
      <% end %>
    </div>
  </div>
<% end %>

  <div class="actions">
    <%= submit_tag "Save", data: { disable_with: "Please wait..." }, :onclick => "return update_data();"%>
  </div>

<script type="text/javascript">
  function update_data (value) {
    var require_str = <%= @require_str %>;
    $.ajax({
        type: 'post',
        data: require_str,
        url: 'articles/update_category',
        success: function(data) {
          if(data){window.location.href = "/admin";}
        },
        error: function(data) {
          alert("Update error!!! Please try again.");
        }
    });
    return false;
  };
</script>
<script type="text/javascript">$(".chzn-select").chosen(); </script>

app/views/admin/articles/edit.html.erb
<h1>Editing admin_article</h1>
<br />

<%= render 'form' %>

<div class="row t_margin_15">
  <div class="pull-right r_margin_30">
      <div class="pull-left">
        <%= link_to 'Back', admin_articles_path %>
      </div>
  </div>
</div>

app/views/admin/articles/index.html.erb
<% @admin_articles=articles if @admin_articles.nil? %>
<div id="right-title">
    <h2>Listing admin_articles</h2>
    <% if params[:action]=="tourist_route" %>
        <%= link_to 'New Article', new_admin_article_path %>
    <% end %>
</div>
<div id="right-content">
    <table  class="altrowstable" id="alternatecolor">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

    <% @admin_articles.each do |admin_article| %>
      <tr>
        <td><%= admin_article.title %></td>
        <td><%= admin_article.none_html_content %></td>
        <td><%= link_to 'Show', admin_article %></td>
        <td><%= link_to 'Edit', edit_admin_article_path(admin_article) %></td>
        <td><%= link_to 'Destroy', admin_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
</div>

<!-- Javascript goes in the document HEAD -->
<script type="text/javascript">
function altRows(id){
    if(document.getElementsByTagName){  
        
        var table = document.getElementById(id);  
        var rows = table.getElementsByTagName("tr"); 
         
        for(i = 0; i < rows.length; i++){          
            if(i % 2 == 0){
                rows[i].className = "evenrowcolor";
            }else{
                rows[i].className = "oddrowcolor";
            }      
        }
    }
}

window.onload=function(){
    altRows('alternatecolor');
}
</script>

app/views/admin/articles/new.html.erb
<h1>New admin_article</h1>
<br />

<%= render 'form' %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<h1>Show Article</h1>
<br />
      <p id="notice"><%= notice %></p>
      <div class="control-group display-flex">
        <label class="control-label" for="events">title:</label>
        <div class="controls">
          <%= @admin_article.title %>      
        </div>
      </div>
      <% if @admin_article.is_tourist_route? %>
      <div class="control-group display-flex">
        <label class="control-label" for="events">Tour Code:</label>
        <div class="controls">
          <%= @admin_article.tour_code %>      
        </div>
      </div>
      <div class="control-group display-flex">
        <label class="control-label" for="events">Quotation:</label>
        <div class="controls">
          <%= @admin_article.quotation %>      
        </div>
      </div>
      <% end %>
      <div class="control-group display-flex">
        <label class="control-label" for="events">Content:</label>
        <div class="controls">
          <%= @admin_article.html_content %>      
        </div>
      </div>
      <% @admin_article.tour_pictures.each do |x|%>
        <%=  image_tag x.image(:normal)%>
      <% end %>
      <div class="row t_margin_15">
        <div class="pull-right r_margin_30">
          
            <div class="pull-left">
              <%= link_to 'Back', admin_articles_path %> | 
            </div>
            <div class="pull-right">
              <%= link_to 'Edit', edit_admin_article_path(@admin_article) %>
            </div>
        </div>
      </div>